#!/usr/bin/env python3
"""Build the Clone Systems CRA pilot deck (scenario 04) on the CYBERFORT template.

Usage:
    python3 scripts/build_pilot_deck.py [path/to/template.pptx]

The template defaults to the pilot template kept one level above the repo. Screenshots
come from 04-clonesystems-seuxdr-siem/presentation/assets/ and are regenerated by
scripts/capture_s4_platform.py.
"""

import os
import sys
from pathlib import Path

from pptx import Presentation
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

sys.path.insert(0, str(Path(__file__).resolve().parent))

from deckkit import (AMBER, BAND_L, BAND_R, BAND_W, BLUE, CYAN, GREEN, GREY, INK,
                     LINE, MAJOR, MINOR, MUTED, NAVY, OLIVE, RED, WASH, WASH_A,
                     WASH_G, WASH_R, WHITE, BOT, KICK_Y, TOP, Pristine,
                     accent_rule, bar, card, content_slide, framed_picture, kicker,
                     nudge_content, placeholder, reorder, retext, set_title,
                     stat_tile, text)

REPO = Path(__file__).resolve().parent.parent
SCENARIO = REPO / "04-clonesystems-seuxdr-siem"
SHOTS = SCENARIO / "presentation" / "assets"
OUT = SCENARIO / "presentation" / "31072026_clone_systems_pilot.pptx"
TEMPLATE = Path(
    sys.argv[1] if len(sys.argv) > 1
    else os.environ.get("PILOT_TEMPLATE",
                        REPO.parent / "31072026_clone_systems_pilot.pptx"))
if not TEMPLATE.is_file():
    raise SystemExit(f"template not found: {TEMPLATE}\n"
                     "Pass it as an argument or set PILOT_TEMPLATE.")

prs = Presentation(str(TEMPLATE))
cover = prs.slides[0]
thanks = prs.slides[3]

# The template ships two identical branded content slides. Consume both before
# cloning, so no slide part is ever deleted — deleting one frees a partname that
# python-pptx then reuses, producing duplicate entries in the saved package.
PRISTINE = Pristine(prs, 1)
_POOL = [prs.slides[1], prs.slides[2]]


def slide(title, **kw):
    proto = _POOL.pop(0) if _POOL else PRISTINE.stamp(prs)
    return content_slide(prs, title, proto=proto, **kw)

# ------------------------------------------------------------------ 1. cover
for shp in cover.shapes:
    if shp.name == "TextBox 5":
        retext(shp, ["CLONE SYSTEMS  PILOT", "31 July 2026  ·  Larnaka, Cyprus"])
    elif shp.name == "TextBox 8":
        retext(shp, ["Georgios Koutidis", "Clone Systems CY, LTD."])
    elif shp.name == "Subtitle 2":
        retext(shp, ["CRA readiness assessment of SEUXDR"])

# ------------------------------------------------------------------ 2. one slide
s = slide("The pilot in one slide")
kicker(s, BAND_L, KICK_Y, "Executive summary  ·  February – July 2026  ·  pilot review 31 July 2026")
tiles = [
    ("7%", "Where we started", "2 of 30 CRA objectives\ncompliant, 29 July", RED, WASH_R),
    ("70%", "Where we are now", "21 of 30 compliant, 30 July\nafter one remediation sprint", GREEN, WASH_G),
    ("52/52", "Conformity questions answered", "every answer evidenced\nagainst a file and line", NAVY, WASH),
    ("6 months", "Engagement span", "February to July 2026\nscope, baseline, remediate, re-assess", NAVY, WASH),
]
tw, gap = 2.865, 0.20
for i, (v, lab, note, vc, fill) in enumerate(tiles):
    stat_tile(s, BAND_L + i * (tw + gap), 2.02, tw, 1.62, v, lab, note,
              value_color=vc, fill=fill, value_size=32)
cols = [
    ("What we did", BLUE,
     "Ran the complete CRA manufacturer workflow in CyberFort against our own "
     "product — scope, classification, SBOM, dependency and SAST scanning, risk "
     "register, VEX, the six Technical File areas, the 52-question conformity "
     "assessment, all 30 objectives, gap analysis and DoC readiness."),
    ("What we found", AMBER,
     "Four blockers that prevented a Declaration of Conformity, and nine conformity "
     "claims we could defend from code. The blockers sat in access control and in the "
     "Annex I Part II vulnerability-handling apparatus — not in the product's "
     "security engineering."),
    ("What we did about it", GREEN,
     "A remediation sprint in the second half of the engagement: 60 files, 8,261 lines. "
     "Disclosure policy, SBOM in CI, authentication restored, remediation targets "
     "validated. Re-assessed in the platform: 21 of 30 objectives compliant. "
     "Annex III Class I still requires a notified body."),
]
cw = 3.887
for i, (head, accent, body) in enumerate(cols):
    x = BAND_L + i * (cw + 0.19)
    card(s, x, 3.78, cw, 2.28, fill=WHITE, line=LINE)
    bar(s, x, 3.78, cw, 0.055, accent)
    text(s, x + 0.22, 3.96, cw - 0.44, 0.34, head, size=14.5, color=NAVY,
         bold=True, font=MAJOR)
    text(s, x + 0.22, 4.36, cw - 0.44, 1.6, body, size=11, color=INK, spacing=1.16)

# ------------------------------------------------------------------ 2b. where we started
s = slide("Where we started: 7% CRA ready")
kicker(s, BAND_L, KICK_Y, "Baseline recorded 29 July 2026  ·  the position we had to establish before we could improve it")

# headline number
card(s, BAND_L, 1.98, 2.92, KICK_Y, fill=WASH_R, line=RED, line_w=1.0)
text(s, BAND_L + 0.22, 2.06, 2.48, 0.86, "7%", size=50, color=RED, bold=True,
     font=MAJOR, spacing=0.85)
text(s, BAND_L + 0.22, 2.90, 2.48, 0.28, "Not Yet Ready", size=13, color=RED, bold=True)
text(s, BAND_L + 0.22, 3.16, 2.60, 0.42,
     "60% objectives + 40% assessment.\nTenant-aggregated: 30 of 270 compliant.", size=8.2,
     color=MUTED, spacing=1.05)


def mini_bar(sl, x, y, w, segs, label, total_label):
    text(sl, x, y, w - 0.7, 0.24, label, size=10.5, color=NAVY, bold=True)
    text(sl, x, y, w, 0.24, total_label, size=9, color=MUTED, align=PP_ALIGN.RIGHT)
    xx, total = x, sum(v for v, _, _ in segs)
    for v, col, _ in segs:
        bar(sl, xx, y + 0.28, w * v / total, 0.22, col)
        xx += w * v / total
    lx = x
    for v, col, name in segs:
        text(sl, lx, y + 0.52, 1.6, 0.22, f"{v} {name}", size=8.5, color=col, bold=True)
        lx += 1.12


card(s, 3.68, 1.98, 3.22, KICK_Y, fill=WHITE, line=LINE)
mini_bar(s, 3.88, 2.08, 2.82,
         [(2, GREEN, "compliant"), (10, AMBER, "partial"), (18, RED, "not")],
         "CRA objectives", "of 30")
mini_bar(s, 3.88, 2.80, 2.82,
         [(2, GREEN, "Yes"), (19, AMBER, "Partially"), (31, RED, "No")],
         "Conformity answers", "of 52")

# takeaway
card(s, BAND_L, 3.66, 6.26, 2.42, fill=NAVY, line=None)
text(s, BAND_L + 0.3, 3.82, 5.66, 0.34,
     "A complete assessment showing 7% is where improvement starts.", size=14,
     color=WHITE, bold=True, font=MAJOR)
for i, line in enumerate([
        "It is not a failure of the assessment — it is the assessment working.",
        "The score is live: it moves as objectives are evidenced and answers change.",
        "Scoped to SEUXDR: 2 of 30 CRA objectives compliant — recorded in the platform, not estimated.",
        "Learning this from our own platform, before a notified body or a market-surveillance "
        "authority does, is the outcome CYBERFORT exists to produce.",
        "Two further gaps surface here: no notified body engaged, and no single product version "
        "to declare — agent 1.0.1, front end 0.0.0, manager unversioned."]):
    text(s, BAND_L + 0.3, 4.24 + i * 0.37, 0.14, 0.3, "—", size=9.5, color=CYAN)
    text(s, BAND_L + 0.52, 4.22 + i * 0.37, 5.44, 0.4, line, size=9.5, color=WHITE,
         spacing=1.05)

framed_picture(s, str(SHOTS / "doc_readiness_crop.png"), 7.22, 1.98, 5.42)

# ------------------------------------------------------------------ 3. product
s = slide("The product under assessment")
kicker(s, BAND_L, KICK_Y, "SEUXDR  ·  Clone Systems, Inc.  ·  economic operator: manufacturer")
facts = [
    ("Product", "SEUXDR — self-hosted SIEM/XDR with AI-driven remediation"),
    ("Release", "main @ 00a95ad · agent 1.0.1 · registered as asset SEUXDR v3.4"),
    ("Stack", "Go 1.23 manager + agent · React 19 front end · Wazuh 4.11 +\nOpenSearch detection · Ollama phi4:14b for analysis"),
    ("Endpoints", "Windows (Event Log) · Linux (journald) · macOS (Unified Logging)"),
    ("Remediation", "BLOCK_IP · KILL_PROCESS · DELETE_FILE — executed on the host"),
    ("Differentiator", "the LLM runs in-network; customer telemetry never reaches\na third-party cloud model"),
]
y = 2.06
card(s, BAND_L, 1.98, 6.45, 4.10, fill=WHITE, line=LINE)
for label, val in facts:
    text(s, BAND_L + 0.24, y + 0.10, 1.42, 0.3, label, size=10.5, color=BLUE, bold=True)
    text(s, BAND_L + 1.74, y + 0.08, 4.5, 0.66, val, size=11, color=INK, spacing=1.14)
    y += 0.66
# architecture sketch
ax = 7.42
text(s, ax, 1.98, 5.28, 0.3, "As-built architecture", size=12, color=NAVY, bold=True, font=MAJOR)
nodes = [
    ("Endpoint agents", "Windows · Linux · macOS", WASH, NAVY),
    ("Manager  ·  :8081 mTLS enrolment  ·  :8443 TLS API + WebSocket", "Wazuh 4.11 · OpenSearch · SQLite", WASH, NAVY),
    ("Ollama  ·  :11434", "phi4:14b, local inference only", WASH_G, GREEN),
]
ny = 2.40
for i, (title_t, sub, fill, accent) in enumerate(nodes):
    h = 0.86
    card(s, ax, ny, 5.28, h, fill=fill, line=LINE)
    bar(s, ax, ny, 0.055, h, accent)
    text(s, ax + 0.24, ny + 0.16, 4.9, 0.42, title_t, size=11.5, color=NAVY,
         bold=True, spacing=1.05)
    text(s, ax + 0.24, ny + 0.55, 4.9, 0.3, sub, size=10, color=MUTED)
    if i < len(nodes) - 1:
        text(s, ax + 2.4, ny + h + 0.02, 0.5, 0.3, "↓", size=13, color=GREY)
    ny += h + 0.26
card(s, ax, 5.56, 5.28, 0.52, fill=WASH_A, line=LINE)
text(s, ax + 0.22, 5.67, 4.9, 0.34,
     "Front end :8080 — unreachable as shipped: no /api/login route exists",
     size=10.5, color=AMBER, bold=True)

# ------------------------------------------------------------------ 4. scope
s = slide("CRA scope: the answer that shapes everything")
kicker(s, BAND_L, KICK_Y, "CRA Scope Assessment  ·  Annex III classification")
card(s, BAND_L, 1.98, BAND_W, 0.86, fill=NAVY, line=None)
text(s, BAND_L + 0.3, 2.14, BAND_W - 0.6, 0.56,
     "ANNEX III  ·  Important product with digital elements  ·  CLASS I",
     size=20, color=WHITE, bold=True, font=MAJOR)
text(s, BAND_L, 3.00, BAND_W, 0.3,
     "The classification is over-determined — three independent Annex III limbs apply:",
     size=11.5, color=INK)
limbs = [
    ("SIEM system", "Bundles Wazuh 4.11 inside its own image. Centralised multi-tenant "
     "event collection, storage and query; MITRE ATT&CK enrichment and STIX 2.1 export."),
    ("Intrusion detection\nand prevention", "Self-declared HIDS. Prevention is implemented, not just "
     "detection — BLOCK_IP installs firewall DROP rules on the endpoint."),
    ("Removes or quarantines\nmalicious software", "Malware-triggered DELETE_FILE executes on the "
     "endpoint as root, dispatched from the manager."),
]
cw = 3.887
for i, (head, body) in enumerate(limbs):
    x = BAND_L + i * (cw + 0.19)
    card(s, x, 3.40, cw, 1.52, fill=WHITE, line=LINE)
    bar(s, x, 3.40, cw, 0.055, BLUE)
    text(s, x + 0.22, 3.56, cw - 0.44, 0.5, head, size=12.5, color=NAVY, bold=True,
         font=MAJOR, spacing=0.98)
    text(s, x + 0.22, 4.16, cw - 0.44, 0.7, body, size=10, color=INK, spacing=1.14)
card(s, BAND_L, 5.06, BAND_W, 1.02, fill=WASH_R, line=RED, line_w=1.0)
text(s, BAND_L + 0.3, 5.17, BAND_W - 0.6, 0.32,
     "Consequence — Article 32(2)", size=13, color=RED, bold=True, font=MAJOR)
text(s, BAND_L + 0.3, 5.53, BAND_W - 0.6, 0.5,
     "A Module A internal-control self-declaration is not a legal option for this product. "
     "We must engage a notified body, or apply harmonised standards in full once they exist. "
     "Every downstream compliance decision has to be built around that — and it is the single "
     "most consequential output of the whole pilot.",
     size=11, color=INK, spacing=1.14)

# ------------------------------------------------------------------ 5. workflow
s = slide("What CyberFort ran, end to end")
kicker(s, BAND_L, KICK_Y, "One working day  ·  twelve steps  ·  one live compliance chain")
phases = [
    ("Scope &\nregister", BLUE, [
        "CRA Scope Assessment wizard",
        "Register SEUXDR with Criticality,\nCRA Vertical Profile, Economic Operator",
        "Seed the CRA framework and its\npre-built risk / control / policy chain",
    ]),
    ("Discover &\nevidence", CYAN, [
        "SBOM Generator (Syft) — the\nproduct's first ever SBOM",
        "Dependency Check (OSV) on go.mod\nand package-lock.json",
        "Code Analysis (Semgrep) on the\nreal Go and TypeScript source",
        "Triage in Scan Findings → Link to Risk;\npublish CycloneDX VEX",
    ]),
    ("Assess &\ndocument", OLIVE, [
        "Six CRA Technical File areas",
        "52-question conformity assessment,\nevidence on every answer",
        "Compliance status for all 30 objectives",
        "Evidence Library with integrity\nverification",
    ]),
    ("Declare &\nplan", GREEN, [
        "Gap analysis + compliance chain map",
        "EU Declaration of Conformity\nreadiness score",
        "CE Marking Checklist",
        "Seven-document readiness pack +\nranked remediation backlog",
    ]),
]
cw = 2.865
for i, (head, accent, items) in enumerate(phases):
    x = BAND_L + i * (cw + 0.20)
    card(s, x, 1.98, cw, 4.08, fill=WHITE, line=LINE)
    bar(s, x, 1.98, cw, 0.055, accent)
    text(s, x + 0.2, 2.14, cw - 0.4, 0.56, head, size=13.5, color=NAVY, bold=True,
         font=MAJOR, spacing=0.98)
    yy = 2.82
    for it in items:
        text(s, x + 0.2, yy, 0.16, 0.3, "▪", size=10, color=accent)
        text(s, x + 0.42, yy - 0.015, cw - 0.66, 0.66, it, size=9.8, color=INK,
             spacing=1.12)
        yy += 0.30 + 0.20 * it.count("\n") + 0.14


# ------------------------------------------------------------------ 6. framework
s = slide("The CRA, as the platform actually models it")
kicker(s, BAND_L, KICK_Y, "Frameworks → Objectives  ·  scope: Asset / Product → SEUXDR")
rows = [
    ("Chapter I", "General provisions — scope, Art. 6 + Annex I", "2"),
    ("Chapter II", "Obligations of economic operators — Art. 13, 14, 25, 26", "4"),
    ("Chapter III", "Conformity of the product", "1"),
    ("Chapter V", "Market surveillance — Art. 52, 54, 70", "2"),
    ("ANNEX I", "Essential requirements — objectives 1, 2, 3a–3k", "13"),
    ("Vuln. Handling", "Part II obligations — objectives 1–8", "8"),
]
tx, tw2 = BAND_L, 5.9
card(s, tx, 1.98, tw2, 3.30, fill=WHITE, line=LINE)
bar(s, tx, 1.98, tw2, 0.34, NAVY)
text(s, tx + 0.2, 2.04, 3.0, 0.26, "Chapter", size=10, color=WHITE, bold=True)
text(s, tx + tw2 - 1.0, 2.04, 0.8, 0.26, "Objectives", size=10, color=WHITE,
     bold=True, align=PP_ALIGN.RIGHT)
yy = 2.44
for i, (ch, desc, n) in enumerate(rows):
    if i % 2 == 1:
        bar(s, tx + 0.02, yy - 0.05, tw2 - 0.04, 0.46, WASH)
    emph = ch in ("ANNEX I", "Vuln. Handling")
    text(s, tx + 0.2, yy, 1.55, 0.28, ch, size=10.5,
         color=NAVY if emph else INK, bold=emph)
    text(s, tx + 1.8, yy, tw2 - 2.9, 0.42, desc, size=9.8, color=MUTED, spacing=1.05)
    text(s, tx + tw2 - 1.0, yy - 0.02, 0.8, 0.28, n, size=13 if emph else 11.5,
         color=NAVY if emph else INK, bold=True, align=PP_ALIGN.RIGHT, font=MAJOR)
    yy += 0.47
card(s, tx, 5.40, tw2, 0.68, fill=WASH, line=LINE)
text(s, tx + 0.2, 5.50, tw2 - 0.4, 0.56,
     "30 objectives in the asset scope  ·  52 conformity questions  ·  each objective carries "
     "seeded policy templates, an evidence upload and a compliance status.",
     size=10.5, color=INK, spacing=1.12)
framed_picture(s, str(SHOTS / "objectives.png"), 6.86, 1.98, 5.84,
               caption="Annex I objectives 3a–3k for SEUXDR, with linked policies and evidence state")

# ============================================================ WALKTHROUGH  W1-W6
# One slide per workflow step, each carrying the real platform screen it was done on.

def walkthrough(title, kick, shot, caption, blocks, note=None,
                left_w=5.18, shot_x=6.02, shot_y=1.96, shot_w=6.55):
    """Left column of callout blocks, one large framed screenshot on the right."""
    sl = slide(title)
    kicker(sl, BAND_L, KICK_Y, kick)
    yy = 1.96
    for head, body, accent in blocks:
        h = 4.08 / len(blocks) - 0.10
        card(sl, BAND_L, yy, left_w, h, fill=WHITE, line=LINE)
        bar(sl, BAND_L, yy, 0.055, h, accent)
        text(sl, BAND_L + 0.24, yy + 0.12, left_w - 0.46, 0.3, head, size=11.5,
             color=NAVY, bold=True, font=MAJOR)
        text(sl, BAND_L + 0.24, yy + 0.46, left_w - 0.44, h - 0.54, body, size=9.5,
             color=INK, spacing=1.10)
        yy += h + 0.10
    framed_picture(sl, str(SHOTS / shot), shot_x, shot_y, shot_w, caption=caption)
    if note:
        text(sl, BAND_L, 6.18, BAND_W, 0.3, note, size=9.6, color=MUTED)
    return sl


walkthrough(
    "Step 1 · Register the product and pin its classification",
    "Assets / Products → Manage Assets  ·  CRA mode enabled",
    "asset_modal_crop.png",
    "Add New Asset — the CRA fields appear only when CRA mode is on for the tenant",
    [("Criticality", "The verbatim option “Security information and event management (SIEM) "
      "systems”, under the ANNEX III – Class I group header. It drives the Technical File "
      "pages, the CE checklist and the DoC score. Leave it blank and every CRA module stays inert.", RED),
     ("CRA Vertical Profile", "“Anti-Malware / Malware Detection Product” — the second Annex III "
      "limb, recorded so the classification argument is visible in the asset record itself "
      "rather than buried in a report.", BLUE),
     ("Economic Operator", "Manufacturer. It determines which obligations apply: Articles 13, "
      "14, 25 and 26 rather than the importer or distributor set.", BLUE),
     ("Justification", "Free text, and worth writing properly — it is the first thing an "
      "assessor reads when asking why you chose Class I over Class II.", CYAN)],
    left_w=5.96, shot_x=7.25, shot_w=5.10)

walkthrough(
    "Step 2 · Seed the framework — and inherit the whole chain",
    "Frameworks → Configuration → Manage Frameworks  ·  include pre-built chain links",
    "framework_select.png",
    "Frameworks → Objectives — selecting CRA from the six frameworks seeded in the tenant",
    [("One dropdown, one checkbox", "Pick CRA from the framework template list, leave "
      "“Include pre-built chain links” enabled, click Add Selected Framework. That single "
      "action seeds the objective tree and the entire connected library.", BLUE),
     ("What it creates for you", "For the CRA framework the tenant now links 45 risks, "
      "98 controls, 48 policies and 330 objective links across 9 assets. Controls arrive as "
      "Baseline Controls and CRA Horizontal Controls (codes like CRA-SD-1, CRA-VH-1); policies "
      "arrive as Draft with their body text already written.", GREEN),
     ("Why it matters", "Nothing after this step was written from a blank page. The rest of the "
      "pilot is reviewing and evidencing seeded entities rather than authoring them — the "
      "difference between a compliance programme you can start today and one you start next "
      "quarter.", CYAN)])

walkthrough(
    "Step 3 · Generate the SBOM the product never had",
    "Security Tools → SBOM Generator (Syft)  ·  ZIP upload or GitHub URL",
    "sbom2_result.png",
    "The real run: 301 components across 4 licences, generated in 23 seconds",
    [("The finding", "SEUXDR shipped no SBOM. The closest artefact was a hand-maintained "
      "26-entry licence list that still held its template placeholder and omitted almost every "
      "indirect dependency.", RED),
     ("Why it blocks a DoC", "Annex I Part II(1) requires a component inventory covering at "
      "least top-level dependencies, in a commonly used machine-readable format. It is the "
      "hard blocker behind questions 38, 39 and 40.", AMBER),
     ("What the run produced", "301 components, 298 libraries and 3 files, across 4 licences — "
      "BSD-3-Clause, MIT, Unlicense and ISC — in 23.26 seconds from the repository archive. "
      "It also surfaced the sabotaged faker package sitting in production dependencies.", GREEN),
     ("What we did next", "CI now regenerates CycloneDX SBOMs on every build and attaches them "
      "to releases; SBOM_POLICY.md commits to cadence, version tracking and delivery.", CYAN)],
    shot_w=5.90)

walkthrough(
    "Step 4 · Scan the real codebase",
    "Security Tools → Dependency Check (OSV) and Code Analysis (Semgrep)",
    "dep_done_640.png",
    "Scan Results after the run — dependency_scan COMPLETED against the product, 34.15 s",
    [("What we scanned", "github.com/CyberGuardEU/t4.4_siem_ai_remediation at commit 00a95ad. "
      "The private-repository route needs a GitHub token, so the run used the source archive of "
      "that exact commit.", BLUE),
     ("OSV — dependency findings", "golang-migrate v3.5.4+incompatible, from 2018 when upstream "
      "is v4. gorilla/websocket v1.4.2, from 2020 — and it carries the remediation command "
      "channel.", AMBER),
     ("Semgrep — code findings", "Critical: a live admin credential committed in three tracked "
      "files. High: no authentication on any API route; private keys written 0644; enrolment "
      "secrets logged in cleartext.", RED),
     ("The compounding factor", "No dependency scanning existed in the repository at all, so "
      "there was no mechanism to learn that any of this was true.", RED)])

# ---- W4: findings → risks → VEX, three screens across
s4 = slide("Step 5 · Findings become risks, and risks become VEX")
kicker(s4, BAND_L, KICK_Y, "Security Tools → Scan Findings  ·  Risks → Risk Register  ·  Security Tools → VEX")
text(s4, BAND_L, 1.98, BAND_W, 0.34,
     "Scan output on its own is an incident report. The chain below is what turns it into "
     "technical documentation — and every hop is a click, not a hand-off.",
     size=11.5, color=INK, spacing=1.1)
_pipe = [
    ("findings.png", "Scan Findings",
     "One filterable table across ZAP, Nmap, Semgrep and OSV, with severity counts, a "
     "remediation toggle and a Link to Risk action per finding. Link to Risk is what feeds "
     "the Compliance Chain — an unlinked finding is invisible to the gap analysis.", CYAN),
    ("risks.png", "Risk Register",
     "Five blocking risks filed against SEUXDR, each linked from its finding and scored for "
     "likelihood, severity and residual risk.", AMBER),
    ("vex.png", "VEX Statements",
     "CycloneDX VEX — how you tell downstream users that a CVE in your SBOM is not "
     "exploitable in your product.", GREEN),
]
_w = 3.85
for i, (shotf, head, body, accent) in enumerate(_pipe):
    x = BAND_L + i * (_w + 0.235)
    framed_picture(s4, str(SHOTS / shotf), x, 2.46, _w)
    bar(s4, x, 4.72, _w, 0.055, accent)
    text(s4, x, 4.86, _w, 0.28, head, size=12.5, color=NAVY, bold=True, font=MAJOR)
    text(s4, x, 5.18, _w, 0.86, body, size=9.6, color=INK, spacing=1.12)
    if i < 2:
        text(s4, x + _w + 0.055, 3.20, 0.2, 0.3, "→", size=15, color=GREY)


walkthrough(
    "Step 6 · Populate the CRA Technical File",
    "Documents → Technical File  ·  six areas, reachable only by sidebar navigation",
    "tf_vd.png",
    "Vulnerability Disclosure — one of six pages, and the one that cites the Article 14 ENISA duty",
    [("Six pages, six specifications", "SBOM Management · Secure SDLC Evidence · Security Design · "
      "Patch & Support Policy · Vulnerability Disclosure · Dependency Policy. Each lists the "
      "numbered requirements the CRA expects you to document and cites the Article or Recital "
      "behind them.", BLUE),
     ("Where SEUXDR stood", "One of the six had an artefact after Step 3 — the SBOM. The other "
      "five had no corresponding documentation at all: no threat model, no CI security gates, no "
      "declared support period, no disclosure policy, no dependency governance.", RED),
     ("Why the pages earn their keep", "They are a specification for the writing you owe, in the "
      "regulator's own order. Paired with the seeded policy templates from Step 2, adopting a "
      "policy takes minutes instead of a week of drafting.", GREEN)])

walkthrough(
    "Step 7 · The 52-question conformity assessment",
    "Assessments  ·  Framework CRA  ·  Type Conformity  ·  Scope Asset → SEUXDR",
    "questions.png",
    "Each question carries an answer, a policy assignment, an evidence description and attachments",
    [("How it works", "52 mandatory questions, paginated ten per page. Yes / No / Partially / "
      "N/A, an Assign Policy selector, an Evidence Description and Attach File(s). The "
      "Completed flag flips only once a valid answer is saved.", BLUE),
     ("The result", "2 Yes · 19 Partially · 31 No. Q29 (availability after an incident) and "
      "Q34 (security-relevant information recording) are honest Yes answers backed by code — "
      "claim them, with evidence. Never answer “Partially” where the evidence supports only "
      "“No” — the score is not a grade, it is the input to a remediation plan.", AMBER),
     ("Suggest from Scans / AI Suggest Answers", "Both toolbar actions pre-populate answers "
      "from the scanner output filed in steps 3–5. Used on Q13, Q38 and Q39 the OSV and SBOM "
      "results feed them directly.", GREEN)])

# ------------------------------------------------------------------ 7. claims
s = slide("What we could legitimately claim")
kicker(s, BAND_L, KICK_Y, "Nine evidence-backed conformity claims  ·  a deck of only failures is a bug list, not an assessment")
claims = [
    ("Modern authenticated encryption throughout",
     "AES-GCM with random per-message nonces; RSA-OAEP-SHA256 key wrapping; per-agent key "
     "isolation. A repository-wide review found no ECB, no unauthenticated CBC and no static IV.",
     "Annex I 3c · 3d  →  Q24, Q25"),
    ("Availability and resilience — answered Yes",
     "Failed-alert queue with exponential backoff, a dead-letter queue for analyst review, and "
     "resume-after-restart state tracking. The best-engineered subsystem in the product.",
     "Annex I 3f  →  Q29, Q30"),
    ("Security-event recording — answered Yes",
     "Structured JSON logging with request correlation IDs, plus a fully persisted AI reasoning "
     "trail including react_history. Explainability better than typical for this product class.",
     "Annex I 3j  →  Q34, Q35"),
    ("Structural blast-radius limitation",
     "Remediation is strictly per-agent: no fleet-wide action primitive exists anywhere in the "
     "codebase, so one bad AI decision cannot cascade. Structural, not configurational.",
     "Annex I 3g · 3i  →  Q31, Q33"),
]
cw, ch2 = 5.935, 1.92
for i, (head, body, tag) in enumerate(claims):
    x = BAND_L + (i % 2) * (cw + 0.19)
    yy = 1.98 + (i // 2) * (ch2 + 0.20)
    card(s, x, yy, cw, ch2, fill=WASH_G, line=LINE)
    bar(s, x, yy, cw, 0.055, GREEN)
    text(s, x + 0.24, yy + 0.18, cw - 0.48, 0.34, head, size=13, color=NAVY,
         bold=True, font=MAJOR)
    text(s, x + 0.24, yy + 0.60, cw - 0.48, 0.92, body, size=10.5, color=INK, spacing=1.14)
    text(s, x + 0.24, yy + ch2 - 0.42, cw - 0.48, 0.3, tag, size=9.5, color=GREEN, bold=True)


# ------------------------------------------------------------------ 8. blockers
s = slide("What blocks market placement")
kicker(s, BAND_L, KICK_Y, "Four blockers  ·  the assessed artefact is the auth-stripped build, so 01 and 02 are properties of that build")
blockers = [
    ("01", "No user authentication, authorisation or accountability",
     "The shipped build has no auth middleware, no login route and no user/role/session schema — "
     "removed deliberately on 29 Oct 2025. All 22 API routes are open, including installer download.",
     "Annex I 3b  ·  Q20, Q21, Q22"),
    ("02", "Unauthenticated remote destructive action across the fleet",
     "The remediation endpoint validates the action verb and nothing else before deleting files, "
     "killing processes or blocking IPs as root — unrate-limited, unattributed, and it bypasses "
     "the manual_only safety mode entirely.",
     "Annex I 3b · 2 · 3d  ·  Q13, Q20, Q26"),
    ("03", "Unvalidated LLM output becomes a root-privileged command argument",
     "The only check on an AI-chosen target is that it is non-empty. No IP validation, no path "
     "canonicalisation, no protected-path denylist. Prompt injection from attacker-controlled log "
     "text is unmitigated.",
     "Annex I 1 · 3d · 3i  ·  Q12, Q25, Q33"),
    ("04", "The entire Annex I Part II apparatus is absent",
     "No SBOM, no SECURITY.md or security contact, no coordinated disclosure policy, no CI, no "
     "dependency scanning, no code signing, no changelog — and no git tags at all.",
     "VH-1 … VH-8  ·  Q38–Q48"),
]
yy = 1.98
for num, head, body, tag in blockers:
    h = 0.98
    card(s, BAND_L, yy, BAND_W, h, fill=WASH_R, line=LINE)
    bar(s, BAND_L, yy, 0.055, h, RED)
    text(s, BAND_L + 0.26, yy + 0.24, 0.6, 0.5, num, size=20, color=RED, bold=True,
         font=MAJOR)
    text(s, BAND_L + 0.95, yy + 0.15, 7.3, 0.32, head, size=13, color=NAVY, bold=True,
         font=MAJOR)
    text(s, BAND_L + 0.95, yy + 0.52, 7.5, 0.48, body, size=10, color=INK, spacing=1.10)
    text(s, BAND_L + 8.75, yy + 0.36, 3.1, 0.4, tag, size=10, color=RED, bold=True,
         align=PP_ALIGN.RIGHT)
    yy += h + 0.07


# ------------------------------------------------------------------ 8b. remediation, four slides

def action_slide(title, kick, points, moved, closing):
    """One remediation workstream at presentation altitude."""
    sl = slide(title)
    kicker(sl, BAND_L, KICK_Y, kick)
    yy = 1.96
    for head, body in points:
        h = 1.16
        card(sl, BAND_L, yy, 8.62, h, fill=WHITE, line=LINE)
        bar(sl, BAND_L, yy, 0.055, h, BLUE)
        text(sl, BAND_L + 0.28, yy + 0.16, 8.0, 0.3, head, size=13, color=NAVY, bold=True,
             font=MAJOR)
        text(sl, BAND_L + 0.28, yy + 0.54, 8.05, 0.56, body, size=10.5, color=INK, spacing=1.12)
        yy += h + 0.12
    card(sl, 9.52, 1.96, 3.18, 2.44, fill=WASH_G, line=LINE)
    text(sl, 9.76, 2.10, 2.7, 0.28, "Objectives moved", size=11.5, color=NAVY, bold=True,
         font=MAJOR)
    my = 2.48
    for label in moved:
        text(sl, 9.76, my, 0.2, 0.26, "\u2713", size=11, color=GREEN, bold=True)
        text(sl, 10.02, my, 2.5, 0.5, label, size=10, color=INK, spacing=1.06)
        my += 0.30 + 0.18 * label.count("\n")
    card(sl, 9.52, 4.52, 3.18, 1.56, fill=NAVY, line=None)
    text(sl, 9.76, 4.66, 2.7, 0.26, "Why it counts", size=10.5, color=CYAN, bold=True)
    text(sl, 9.76, 4.96, 2.72, 1.0, closing, size=9.6, color=WHITE, spacing=1.10)
    return sl


action_slide(
    "Remediation 1 — we made it possible to be told",
    "Vulnerability handling  ·  Annex I Part II  ·  the cheapest blocker to close, and it gates the rest",
    [("Published a way to report a vulnerability to us",
      "A monitored security contact, acknowledgement within three working days, triage within ten, "
      "and remediation windows set by severity. Coordinated disclosure with a 90-day default "
      "embargo and public credit for reporters. Before this the readme said \u201ccontact []\u201d."),
     ("Wired the regulator's clock into the process",
      "Article 14 is not advisory: an actively exploited vulnerability means an early warning to "
      "ENISA and the national CSIRT within 24 hours, a full notification within 72, and a final "
      "report within 14 days. That runbook now exists, with named roles and an evidence pack."),
     ("Made the component inventory automatic",
      "CycloneDX SBOMs are generated for the Go module and the front end on every build and "
      "attached to every release. govulncheck, npm audit, Trivy and gitleaks run on push and "
      "weekly. Dependabot covers Go, npm, Docker and the actions themselves.")],
    ["VH-1  components and SBOM", "VH-2  remediate without delay",
     "VH-3  regular testing", "VH-4  public disclosure",
     "VH-5  disclosure policy", "VH-6  contact address",
     "VH-8  update dissemination"],
    "Six of the eight Vulnerability Handling objectives had no supporting artefact at all. This was "
    "days of work, not months, and it moved more objectives than anything else we did.")

action_slide(
    "Remediation 2 — we wrote the file an assessor asks for",
    "Technical documentation  ·  Article 13 and Annex V  ·  nine documents, dated, owned and reviewable",
    [("A real cybersecurity risk assessment",
      "Intended purpose and reasonably foreseeable misuse, the operational environment, the assets "
      "protected, expected service life, and a documented scoring method. Eighteen risks with "
      "inherent and residual ratings \u2014 and an applicability determination for every Annex I "
      "requirement, because the CRA demands a justification for anything excluded."),
     ("Threats modelled, not asserted",
      "STRIDE across the four trust boundaries that actually exist in the product, an "
      "attack-surface inventory listing every port with its authentication state, and the rationale "
      "behind each cryptographic choice. An assessor can disagree with a documented decision; they "
      "cannot evaluate an undocumented one."),
     ("A support commitment with a date on it",
      "Five years, to 30 July 2031, which is the CRA minimum. Patch windows by severity, a "
      "12-month end-of-support notice and an emergency zero-day runbook. The product previously "
      "declared no support period and had no version identifier for the manager at all.")],
    ["Ch II Art. 13  manufacturer\nobligations", "Ch II Art. 25  internal\nprocesses",
     "Ch II Art. 26  user guidance", "Annex I 3k  security updates"],
    "Nine of the 52 conformity questions ask about the risk assessment alone. None had an answer "
    "before this, and no amount of good engineering substitutes for the document.")

action_slide(
    "Remediation 3 — we closed the finding that stops an audit",
    "Access control and attribution  ·  Annex I 2(b)  ·  what a market-surveillance authority opens with",
    [("The manager API was entirely unauthenticated",
      "All 22 routes on the TLS listener were open \u2014 organisation creation, agent generation, "
      "installer download with embedded private keys, alert content, and the endpoint that deletes "
      "files on endpoints. Authentication now gates the group, and fails closed rather than open "
      "if it is not configured."),
     ("We used what was already in the repository",
      "The RS256 signing and validation code had been written and then never connected to a route. "
      "The password policy was written and never imported. Restoring the control was largely "
      "wiring \u2014 worth knowing before anyone budgets a rewrite."),
     ("Destructive actions are attributable and authorised",
      "Every remediation command records the operator principal and the source address. The route "
      "that deletes files and kills processes is gated on an administrator or operator role \u2014 "
      "authorised, not merely reachable by anyone holding a token.")],
    ["Annex I 3b  protection from\nunauthorised access",
     "Annex I 2  no known exploitable\nvulnerabilities",
     "Q20, Q21, Q22 answered Yes"],
    "One honest limit: organisation scoping is not implemented, so a 3.4.x manager must run "
    "single-tenant. That is recorded as a deployment requirement and a risk, not presented as a "
    "control we have.")

action_slide(
    "Remediation 4 — we stopped trusting the model's output",
    "Remediation safety  ·  Annex I 2(a) and 2(i)  ·  the risk that is specific to an AI-driven product",
    [("Targets are validated by type, not just for emptiness",
      "Before this the only check on an AI-chosen target was that the string was not empty \u2014 and "
      "it flowed to rm -f, pkill and pfctl running as root. Now an IP must be routable and public, "
      "a path is canonicalised and refused inside a protected prefix, and a process name is checked "
      "against a list that includes the agent itself and the host's init."),
     ("Validated twice, deliberately",
      "The agent re-checks every target before it executes, because an endpoint must not assume the "
      "manager validated anything. Sixty-three test cases cover the rules, and response scripts run "
      "under a timeout instead of an unbounded exec."),
     ("The safe default is now the default",
      "An absent configuration key used to mean fully automatic remediation. It now means "
      "manual_only, and every dispatch path honours it \u2014 including the reconnect retry that "
      "previously bypassed the gate entirely.")],
    ["Annex I 1  appropriate\ncybersecurity", "Annex I 3a  secure by default",
     "Annex I 3d  integrity", "Annex I 3i  incident impact"],
    "Prompt injection through log content is the attack this closes: anyone who could write a log "
    "line could previously influence which host action ran.")

# ------------------------------------------------------------------ 8c. re-assessment
s = slide("The re-assessment: 70% CRA ready")
kicker(s, BAND_L, KICK_Y, "Frameworks → Objectives  ·  CRA  ·  asset scope SEUXDR  ·  30 July 2026")
card(s, BAND_L, 1.96, 2.92, 1.56, fill=WASH_G, line=GREEN, line_w=1.0)
text(s, BAND_L + 0.22, 2.04, 2.48, 0.86, "70%", size=50, color=GREEN, bold=True,
     font=MAJOR, spacing=0.85)
text(s, BAND_L + 0.22, 2.88, 2.48, 0.28, "21 of 30 objectives", size=13, color=GREEN, bold=True)
text(s, BAND_L + 0.22, 3.16, 2.60, 0.3, "recorded in the platform, not estimated", size=8.6,
     color=MUTED)

card(s, 3.68, 1.96, 3.22, 1.56, fill=WHITE, line=LINE)
def _bars(x, y, w, label, segs, total):
    text(s, x, y, w - 0.7, 0.24, label, size=10.5, color=NAVY, bold=True)
    text(s, x, y, w, 0.24, total, size=9, color=MUTED, align=PP_ALIGN.RIGHT)
    xx, tot = x, sum(v for v, _, _ in segs)
    for v, col, _ in segs:
        bar(s, xx, y + 0.28, w * v / tot, 0.22, col)
        xx += w * v / tot
    lx = x
    for v, col, nm in segs:
        text(s, lx, y + 0.52, 1.6, 0.22, f"{v} {nm}", size=8.5, color=col, bold=True)
        lx += 1.12
_bars(3.88, 2.06, 2.82, "29 July — baseline",
      [(2, GREEN, "compliant"), (10, AMBER, "partial"), (18, RED, "not")], "of 30")
_bars(3.88, 2.78, 2.82, "30 July — after sprint 1",
      [(21, GREEN, "compliant"), (8, AMBER, "partial"), (1, RED, "not")], "of 30")

card(s, BAND_L, 3.66, 6.26, 2.42, fill=NAVY, line=None)
text(s, BAND_L + 0.3, 3.82, 5.66, 0.34,
     "What the remaining nine objectives are.", size=14, color=WHITE, bold=True, font=MAJOR)
for i, line in enumerate([
        "Eight stay partially compliant on purpose: the database is still unencrypted at rest, "
        "log content is not yet pseudonymised, blocks have no expiry, and releases are not signed.",
        "One stays not compliant: Chapter III. Annex III Class I requires a notified body and we "
        "have not engaged one — no amount of engineering closes that.",
        "No organisation scoping yet, so a 3.4.x manager must run single-tenant — a recorded "
        "deployment requirement, not a control. Agents also 401 until they hold a token.",
        "The tenant-wide DoC readiness widget moved 7% to 11%; it aggregates 270 objectives "
        "across nine products and needs the questionnaire completed to move further."]):
    text(s, BAND_L + 0.3, 4.24 + i * 0.42, 0.14, 0.3, "—", size=9.5, color=CYAN)
    text(s, BAND_L + 0.52, 4.22 + i * 0.42, 5.44, 0.42, line, size=9.4, color=WHITE,
         spacing=1.05)
framed_picture(s, str(SHOTS / "objectives_after_crop.png"), 7.22, 1.96, 5.46,
               caption="Annex I and Vulnerability Handling objectives after the sprint")

# ------------------------------------------------------------------ 8d. timeline
s = slide("Six months, and the number that changed")
kicker(s, BAND_L, KICK_Y, "February – July 2026  ·  every figure below was read from the platform, not estimated")
steps = [
    ("1 month", "Onboard", BLUE,
     "Tenant stood up and the CRA framework seeded with its chain links — 45 risks, 98 controls, "
     "48 policies. Control and policy library imported, and the first scanner runs recorded "
     "against the product repository.",
     "framework in place"),
    ("2 months", "Baseline", AMBER,
     "SEUXDR registered with its Annex III Class I classification and justification. Scans re-run "
     "against commit 00a95ad: SBOM 301 components in 23.26 s, dependency scan 34.15 s. All 30 "
     "objectives graded against code evidence; a 25-item backlog ranked.",
     "2 of 30  ·  7%"),
    ("8 weeks", "Remediation", RED,
     "Sprint 1 committed on branch cra/remediation-sprint-1: 60 files, 8,261 lines. Disclosure "
     "policy, SBOM in CI, nine CRA technical documents, authentication and authorisation restored, "
     "remediation targets validated, permissions tightened, credential removed.",
     "Tier 0 closed"),
    ("1 month", "Re-assessment", GREEN,
     "The same 30 objectives re-graded in the platform against the new evidence. No question was "
     "re-worded and no objective was removed — only the evidence changed.",
     "21 of 30  ·  70%"),
]
_cw = 2.865
for i, (when, head, accent, body, metric) in enumerate(steps):
    x = BAND_L + i * (_cw + 0.20)
    card(s, x, 1.96, _cw, 2.30, fill=WHITE, line=LINE)
    bar(s, x, 1.96, _cw, 0.055, accent)
    text(s, x + 0.2, 2.12, _cw - 0.4, 0.24, when.upper(), size=9.2, color=accent, bold=True)
    text(s, x + 0.2, 2.38, _cw - 0.4, 0.3, head, size=13.5, color=NAVY, bold=True, font=MAJOR)
    text(s, x + 0.2, 2.74, _cw - 0.4, 1.1, body, size=9.2, color=INK, spacing=1.08)
    bar(s, x + 0.2, 3.90, _cw - 0.4, 0.02, LINE)
    text(s, x + 0.2, 3.98, _cw - 0.4, 0.26, metric, size=11, color=accent, bold=True, font=MAJOR)
    if i < 3:
        text(s, x + _cw + 0.035, 2.86, 0.2, 0.3, "→", size=14, color=GREY)

card(s, BAND_L, 4.46, BAND_W, 1.62, fill=WASH, line=LINE)
text(s, BAND_L + 0.26, 4.58, 6.6, 0.28, "What moved across the engagement, measured", size=11.5, color=NAVY,
     bold=True, font=MAJOR)
metrics = [("CRA objectives compliant", "2 / 30", "21 / 30"),
           ("Objectives not compliant", "18 / 30", "1 / 30"),
           ("SBOM components documented", "none", "301"),
           ("Security contact and CVD policy", "none", "published"),
           ("CI pipelines with security gates", "0", "2"),
           ("Declarable product version", "none", "3.4.0")]
for i, (lab, was, now) in enumerate(metrics):
    col = i % 3
    row = i // 3
    x = BAND_L + 0.26 + col * 3.95
    y = 4.92 + row * 0.52
    text(s, x, y, 2.5, 0.24, lab, size=9.2, color=MUTED)
    text(s, x, y + 0.20, 1.0, 0.26, was, size=10.5, color=GREY, bold=True, font=MAJOR)
    text(s, x + 1.02, y + 0.20, 0.24, 0.26, "→", size=9, color=GREY)
    text(s, x + 1.32, y + 0.20, 1.5, 0.26, now, size=10.5, color=GREEN, bold=True, font=MAJOR)

# ------------------------------------------------------------------ 10. artefacts
s = slide("Artefacts that did not exist before the pilot")
kicker(s, BAND_L, KICK_Y, "The readiness pack  ·  seven exportable documents  ·  Annex V technical documentation skeleton")
left = [
    ("Software Bill of Materials",
     "Machine-readable, generated by Syft. The product shipped none — the closest artefact was a "
     "hand-maintained 26-entry licence list that still contained its template placeholder."),
    ("CycloneDX VEX statement set",
     "How we tell downstream users and authorities that a CVE in our SBOM is not exploitable in "
     "our product — the difference between an honest SBOM and an alarming one."),
    ("CRA Technical File across six areas",
     "SBOM management, secure SDLC evidence, security design, patch & support policy, "
     "vulnerability disclosure, dependency policy."),
]
right = [
    ("Risk register scoped to the product",
     "Five blocking risks, each linked from a scan finding to the CRA objective it violates, "
     "traceable through the compliance chain."),
    ("Conformity assessment + objective tree",
     "52 answers and 30 objective statuses, every one carrying an evidence description — "
     "exportable as PDF and CSV."),
    ("Gap analysis and DoC readiness record",
     "Objectives without evidence, objectives not compliant, objectives without linked policies — "
     "plus a live readiness score and a CE Marking Checklist."),
]
for col, items in ((BAND_L, left), (BAND_L + 6.13, right)):
    yy = 1.98
    for head, body in items:
        card(s, col, yy, 5.935, 1.30, fill=WHITE, line=LINE)
        bar(s, col, yy, 5.935, 0.055, CYAN)
        text(s, col + 0.24, yy + 0.18, 0.34, 0.3, "✓", size=13, color=GREEN, bold=True)
        text(s, col + 0.62, yy + 0.17, 5.1, 0.32, head, size=12.5, color=NAVY,
             bold=True, font=MAJOR)
        text(s, col + 0.62, yy + 0.58, 5.1, 0.7, body, size=10, color=INK, spacing=1.12)
        yy += 1.38


# ------------------------------------------------------------------ 11. roadmap
s = slide("Remediation roadmap")
kicker(s, BAND_L, KICK_Y, "25 findings, ranked by how much each blocks a Declaration of Conformity")
tiers = [
    ("Week 1", "Decide and declare", RED,
     "Notified-body route · SECURITY.md and security contact · SBOM in CI · reconcile "
     "documentation with code", "cheapest, highest leverage"),
    ("Weeks 2–4", "Close the access-control blockers", AMBER,
     "Restore auth + RBAC · gate the remediation endpoint and record operator identity · "
     "validate targets · sign releases · encrypt at rest", "makes Q13 and Q20 answerable"),
    ("Weeks 5–8", "Documentation and process", BLUE,
     "Risk assessment and threat model · 5-year support period · data minimisation · "
     "dependency policy · audit-trail attribution", "closes Annex V"),
    ("Then", "Re-run the pilot", GREEN,
     "Re-scan, re-answer, read the new score. The compliance chain is live — repeatability, "
     "not the first score, is the platform's real value.", "target: >70% readiness"),
]
yy = 1.98
for when, head, accent, body, note in tiers:
    h = 0.94
    card(s, BAND_L, yy, 8.62, h, fill=WHITE, line=LINE)
    bar(s, BAND_L, yy, 0.055, h, accent)
    text(s, BAND_L + 0.26, yy + 0.20, 1.5, 0.3, when, size=11.5, color=accent, bold=True)
    text(s, BAND_L + 1.80, yy + 0.14, 4.2, 0.32, head, size=12.5, color=NAVY, bold=True,
         font=MAJOR)
    text(s, BAND_L + 1.80, yy + 0.50, 6.5, 0.4, body, size=9.8, color=INK, spacing=1.10)
    text(s, BAND_L + 6.40, yy + 0.16, 2.0, 0.3, note, size=9.5, color=MUTED,
         align=PP_ALIGN.RIGHT)
    yy += h + 0.09
tgt_x = 9.52
card(s, tgt_x, 1.98, 3.18, 4.08, fill=NAVY, line=None)
text(s, tgt_x + 0.24, 2.14, 2.7, 0.34, "Target after Tier 0–1", size=13, color=WHITE,
     bold=True, font=MAJOR)
metrics = [("Objectives compliant", "2 / 30", "20 / 30"),
           ("Objectives not compliant", "20 / 30", "2 / 30"),
           ("Answers “Yes”", "2 / 52", "34 / 52"),
           ("Objectives with evidence", "0 / 30", "30 / 30"),
           ("DoC readiness", "7%", "> 70%")]
my = 2.66
for label, now, then in metrics:
    text(s, tgt_x + 0.24, my, 2.7, 0.26, label, size=9.5, color=CYAN)
    text(s, tgt_x + 0.24, my + 0.24, 1.2, 0.28, now, size=11.5, color=GREY, bold=True,
         font=MAJOR)
    text(s, tgt_x + 1.42, my + 0.24, 0.3, 0.28, "→", size=10, color=GREY)
    text(s, tgt_x + 1.78, my + 0.24, 1.16, 0.28, then, size=11.5, color=WHITE,
         bold=True, font=MAJOR)
    my += 0.62
text(s, tgt_x + 0.24, 5.76, 2.7, 0.24,
     "3g and 3i stay “partially” on purpose.", size=8.6, color=GREY)

# ------------------------------------------------------------------ 12. value
s = slide("What the pilot proves about the platform")
kicker(s, BAND_L, KICK_Y, "Clone Systems is the CYBERFORT target profile — and we ran it on ourselves")
values = [
    ("Time and cost compression",
     "One engineer, one day, to a complete and defensible position on 30 objectives and 52 "
     "questions. The same position by consulting engagement is several weeks and a five-figure fee."),
    ("Traceability, not a report",
     "Every answer links to a finding, a risk, a control, a policy and an objective. The chain map "
     "shows where the graph has no edges — exactly what the gap analysis reports."),
    ("Repeatable after every release",
     "A consultancy deliverable is a snapshot. This is live: re-scan, re-answer, re-read the score. "
     "That is what turns CRA compliance from a project into a process."),
    ("Honest by construction",
     "The platform gave us 7% and four blockers on our own flagship product. A tool that flatters "
     "you is worthless in front of a notified body."),
]
yy = 1.98
for head, body in values:
    h = 0.97
    card(s, BAND_L, yy, 6.30, h, fill=WHITE, line=LINE)
    bar(s, BAND_L, yy, 6.30, 0.055, BLUE)
    text(s, BAND_L + 0.24, yy + 0.16, 5.8, 0.32, head, size=12.5, color=NAVY,
         bold=True, font=MAJOR)
    text(s, BAND_L + 0.24, yy + 0.49, 5.85, 0.46, body, size=9.6, color=INK, spacing=1.08)
    yy += h + 0.06
framed_picture(s, str(SHOTS / "gap_analysis.png"), 7.30, 1.98, 5.40,
               caption="Compliance Chain → Gap Analysis, framework CRA — exportable as PDF")

# ------------------------------------------------------------------ 13. next steps
s = slide("Next steps")
kicker(s, BAND_L, KICK_Y, "Decisions we need out of this review  ·  full detail in docs/REMEDIATION_BACKLOG.md")
asks = [
    ("Which build goes to market?",
     "The assessed artefact is the authentication-stripped variant. Confirm that the CRA-conformant "
     "target is the full SEUXDR build with JWT and RBAC restored — that single decision changes two "
     "of the four blockers.", "Management  ·  August 2026"),
    ("Approve the notified-body route",
     "Annex III Class I removes self-assessment. We need budget and a shortlist; conformity "
     "assessment lead times are the long pole in any CE-marking plan.", "Management  ·  August 2026"),
    ("Fund the Tier 0 sprint",
     "SECURITY.md, SBOM in CI, dependency scanning, tagged releases and a documentation "
     "reconciliation. Small, mostly tooling, and it moves four objectives.", "Engineering  ·  Q3 2026"),
    ("Re-run the pilot at the end of Tier 1",
     "Same asset, same framework, new score. That second number is the one to take to customers "
     "and to the CYBERFORT consortium.", "Engineering  ·  Q4 2026"),
]
yy = 1.98
for i, (head, body, owner) in enumerate(asks):
    h = 0.98
    card(s, BAND_L, yy, BAND_W, h, fill=WHITE, line=LINE)
    bar(s, BAND_L, yy, 0.055, h, CYAN)
    text(s, BAND_L + 0.26, yy + 0.22, 0.55, 0.44, f"{i + 1}", size=19, color=CYAN,
         bold=True, font=MAJOR)
    text(s, BAND_L + 0.92, yy + 0.16, 7.4, 0.32, head, size=13, color=NAVY, bold=True,
         font=MAJOR)
    text(s, BAND_L + 0.92, yy + 0.53, 8.1, 0.46, body, size=10, color=INK, spacing=1.10)
    text(s, BAND_L + 9.30, yy + 0.36, 2.55, 0.3, owner, size=10, color=BLUE, bold=True,
         align=PP_ALIGN.RIGHT)
    yy += h + 0.07


# ------------------------------------------------------------------ closer
for shp in thanks.shapes:
    if shp.name == "Subtitle 2":
        retext(shp, ["georgios koutidis", "clone systems cy, ltd."])

order = [cover] + [sl for sl in prs.slides if sl not in (cover, thanks)] + [thanks]
reorder(prs, order)

# Every slide is drawn against a 1.96in origin; shift the content down in one pass
# so there is real white space between the navy header and the first card.
nudge_content(prs, dy=TOP - 1.96)

OUT.parent.mkdir(parents=True, exist_ok=True)
prs.save(str(OUT))
print(f"saved {OUT}")
print(f"slides: {len(prs.slides.__iter__.__self__._sldIdLst)}")
for i, sl in enumerate(prs.slides, 1):
    ph = placeholder(sl, 0)
    t = ph.text_frame.text.strip().replace("\n", " ") if ph else "(no title)"
    print(f"  {i:2d}  {t[:70]}")
